INSERT INTO BOOK (AUTHOR, NAME, YEAR) VALUES('Bloch', 'Eff. Java', 2008);
INSERT INTO BOOK (AUTHOR, NAME, YEAR) VALUES('Ivanov', 'Modern PHP', 2010);
INSERT INTO BOOK (AUTHOR, NAME, YEAR) VALUES('Petrov', 'Crazy JS', 2015);
INSERT INTO BOOK (AUTHOR, NAME, YEAR) VALUES('Sidorov', 'Elegant Kotlin', 2017);
INSERT INTO BOOK (AUTHOR, NAME, YEAR) VALUES('Kozlov', 'Big Data', 2016);

-- https://www.dailycred.com/article/bcrypt-calculator
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('admin', '$2a$11$0oq3..9sG0QbLJmKoeLQu.5EUaOTWkFXrUTFxqLc7vcZLq96iw9Yy');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('user', '$2a$11$YhAbtbz5iVaMCwwXAHydwuOoykjCsHw68D0KH2EZILZ4QViiSCKse');

INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('user', 'USER');
