INSERT INTO BOOK (AUTHOR, NAME, YEAR) VALUES('Bloch', 'Eff. Java', 2008);
INSERT INTO BOOK (AUTHOR, NAME, YEAR) VALUES('Ivanov', 'Modern PHP', 2010);
INSERT INTO BOOK (AUTHOR, NAME, YEAR) VALUES('Petrov', 'Crazy JS', 2015);
INSERT INTO BOOK (AUTHOR, NAME, YEAR) VALUES('Sidorov', 'Elegant Kotlin', 2017);
INSERT INTO BOOK (AUTHOR, NAME, YEAR) VALUES('Kozlov', 'Big Data', 2016);
